name = "tamuuid-cdn"
main = "tamuuid-cdn-worker.js"
compatibility_date = "2024-01-27"
workers_dev = false

[[routes]]
pattern = "cdn.tamuu.id"
custom_domain = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tamuu-assets"
