name = "bg-remover"
main = "bg-remover-worker.js"
compatibility_date = "2024-01-01"

# Custom Domain for API
[[routes]]
pattern = "api.tamuu.id"
custom_domain = true

# R2 bucket for temporary image storage
[[r2_buckets]]
bucket_name = "bg-temp"
binding = "R2_BUCKET"
